version: "3"

services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      quiz_bot_network:
        ipv4_address: 172.25.25.101

networks:
  quiz_bot_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.25.0/24